<a href="https://colab.research.google.com/github/omsharma-001/CS683_Assignment1/blob/main/NLP_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!wget https://raw.githubusercontent.com/omsharma-001/CS683_Assignment1/main/cleaned_snippets.csv

--2024-09-17 17:27:16--  https://raw.githubusercontent.com/omsharma-001/CS683_Assignment1/main/cleaned_snippets.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2141441 (2.0M) [text/plain]
Saving to: ‘cleaned_snippets.csv’

cleaned_snippets.cs 100%[===================>]   2.04M  --.-KB/s    in 0.01s   

2024-09-17 17:27:16 (151 MB/s) - ‘cleaned_snippets.csv’ saved [2141441/2141441]



In [12]:
import pandas as pd;
data = pd.read_csv("/content/cleaned_snippets.csv")


In [13]:
data = data.drop(columns = "snippet")

In [14]:
data

sentiment                                    cleaned_snippet
0              1  rock destined 21st centurys new conan hes goin...
1              1  gorgeously elaborate continuation lord rings t...
2              1                          effective tootepid biopic
3              1  sometimes like go movies fun wasabi good place...
4              1  emerges something rare issue movie thats hones...
...          ...                                                ...
10657          0     terrible movie people nevertheless find moving
10658          0  many definitions time waster movie must surely...
10659          0  stands crocodile hunter hurried badly cobbled ...
10660          0          thing looks like madeforhomevideo quickie
10661          0                         enigma wellmade dry placid

[10662 rows x 2 columns]

In [15]:
train_data_pos = data.iloc[:4000]
train_data_neg = data.iloc[-4000:]

In [16]:
train_data_pos

sentiment                                    cleaned_snippet
0             1  rock destined 21st centurys new conan hes goin...
1             1  gorgeously elaborate continuation lord rings t...
2             1                          effective tootepid biopic
3             1  sometimes like go movies fun wasabi good place...
4             1  emerges something rare issue movie thats hones...
...         ...                                                ...
3995          1  less sensational truecrime helljaunt purists m...
3996          1                                film one years best
3997          1               eerily accurate depiction depression
3998          1           delicious crime drama par slickest mamet
3999          1                charming witty also somewhat clumsy

[4000 rows x 2 columns]

In [17]:
train_data = pd.concat([train_data_pos, train_data_neg], ignore_index=True)

In [18]:
train_data = train_data.sample(frac=1, random_state=42)

In [19]:
validation_data_pos = data.iloc[4000:4500]
validation_data_neg = data.iloc[-4000-500:-4000]



In [20]:
validation_data = pd.concat([validation_data_pos, validation_data_neg], ignore_index=True)
validation_data = validation_data.sample(frac=1, random_state=42)

In [21]:
validation_data

sentiment                                    cleaned_snippet
521          0  boring pretentious muddle uses sensational rea...
737          0  hate madonna within films first five minutes l...
740          0                     fascinating choppy documentary
660          0                          formulaic 51st power like
411          1  compelling mix trial movie escape movie unexpe...
..         ...                                                ...
106          1         consummate actor barry done excellent work
270          1  beautifully acted directed clear washington ce...
860          0  scared prospect becks next project lets see ha...
435          1  jones delivered solidly entertaining moving fa...
102          1  questioning election process payami graphicall...

[1000 rows x 2 columns]

In [22]:
test_data_pos = data.iloc[4500:5331]
test_data_neg = data.iloc[-4500-831:-4500]

In [23]:
test_data = pd.concat([test_data_pos, test_data_neg], ignore_index=True)

In [24]:
from sklearn.model_selection import train_test_split
train_sentences = train_data["cleaned_snippet"].to_numpy()
train_labels = train_data["sentiment"].to_numpy()

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization


In [26]:
text_vectorizer = TextVectorization(max_tokens=None, standardize="lower_and_strip_punctuation", split="whitespace",  ngrams=None, output_mode="int", output_sequence_length=None)

In [27]:
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

11

In [28]:
max_vocab_length = 10000
max_length = 20

In [29]:
text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [30]:
text_vectorizer.adapt(train_sentences)

In [31]:
sample_sentence = "There's a flood in my street!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 20), dtype=int64, numpy=
array([[  36,    1,    1,    1,    1, 1655,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]])>

In [32]:
tf.random.set_seed(42)
from tensorflow.keras import layers

In [33]:
embedding = layers.Embedding(input_dim=max_vocab_length,
                             output_dim=128,
                             embeddings_initializer="uniform",
                             input_length=max_length,
                             name="embedding_1")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
import random
random_sentence = random.choice(train_sentences)
print(f"Original text:\n{random_sentence}\
      \n\nEmbedded version:")

sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
shortstory quaint touchingly mending childs pain dead mother via communication old woman straight eudora welty      

Embedded version:


<tf.Tensor: shape=(1, 20, 128), dtype=float32, numpy=
array([[[-0.0169571 , -0.01276488, -0.02208732, ...,  0.00701835,
          0.03139993, -0.03433694],
        [ 0.0406351 , -0.04314729, -0.03024272, ...,  0.02849727,
          0.04440547,  0.02811127],
        [-0.00985115,  0.00341127,  0.00453029, ...,  0.03675758,
         -0.00895443,  0.01251236],
        ...,
        [ 0.00619   , -0.02327647, -0.01244841, ...,  0.03760617,
         -0.00633379, -0.03430296],
        [ 0.00619   , -0.02327647, -0.01244841, ...,  0.03760617,
         -0.00633379, -0.03430296],
        [ 0.00619   , -0.02327647, -0.01244841, ...,  0.03760617,
         -0.00633379, -0.03430296]]], dtype=float32)>

In [35]:
embedding

<Embedding name=embedding_1, built=True>

In [36]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):

  model_accuracy = accuracy_score(y_true, y_pred) * 100

  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                  "precision": model_precision,
                  "recall": model_recall,
                  "f1": model_f1}
  return model_results

In [37]:
from tensorflow.keras import layers
from tensorflow.keras.regularizers import l2

inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GRU(64)(x)
x = layers.Dense(100, activation="relu")(x)
x = layers.Dense(50, activation="relu")(x)
x = layers.Dense(20, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_1 = tf.keras.Model(inputs, outputs, name="model_1_LSTM")

In [38]:
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
                metrics=["accuracy"],
                )

In [39]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [40]:
model_1.summary()

Model: "model_1_LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization_1                 │ (None, 20)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_1 (Embedding)              │ (None, 20, 128)             │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ (None, 64)                  │          37,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 100)                 │           6,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 50)                  │           5,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 20)                  │           1,020 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              21 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,329,839 (5.07 MB)

 Trainable params: 1,329,839 (5.07 MB)

 Non-trainable params: 0 (0.00 B)

In [41]:
val_sentences = validation_data["cleaned_snippet"].to_numpy()
val_labels = validation_data["sentiment"].to_numpy()

In [42]:
model_1_history = model_1.fit(train_sentences,
                              train_labels,
                              validation_data=(val_sentences, val_labels),
                              epochs=50,
                              callbacks = [early_stopping]
                              )

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 24ms/step - accuracy: 0.4962 - loss: 0.6932 - val_accuracy: 0.4950 - val_loss: 0.6932
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - accuracy: 0.5094 - loss: 0.6931 - val_accuracy: 0.4930 - val_loss: 0.6933
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 10s 29ms/step - accuracy: 0.5162 - loss: 0.6929 - val_accuracy: 0.4930 - val_loss: 0.6935
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step - accuracy: 0.5254 - loss: 0.6916 - val_accuracy: 0.5070 - val_loss: 0.6926
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - accuracy: 0.7076 - loss: 0.5740 - val_accuracy: 0.7440 - val_loss: 0.5544
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - accuracy: 0.8728 - loss: 0.3061 - val_accuracy: 0.7450 - val_loss: 0.6059
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - accuracy: 0.9294 - loss: 0.1950 - val_accuracy: 0.7440 - val_loss: 0.6711
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - accuracy: 0.9545 - loss: 0.1389 - val_ac

In [43]:
test_sentences = test_data["cleaned_snippet"].to_numpy()
test_labels = test_data["sentiment"].to_numpy()

In [44]:
model_1_pred_probs = model_1.predict(test_sentences)

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step


In [45]:
model_1_pred_probs.shape, model_1_pred_probs[:10]

((1662, 1),
 array([[0.95161784],
        [0.04138316],
        [0.8090288 ],
        [0.09445893],
        [0.8344238 ],
        [0.6007691 ],
        [0.6518073 ],
        [0.8433952 ],
        [0.448302  ],
        [0.67806864]], dtype=float32))

In [46]:
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 0., 1., 0., 1., 1., 1., 1., 0., 1.], dtype=float32)>

In [47]:
model_1_results = calculate_results(y_true=test_labels,
                                    y_pred=model_1_preds)
model_1_results

{'accuracy': 74.24789410348977,
 'precision': 0.7434321377844524,
 'recall': 0.7424789410348978,
 'f1': 0.7422266029845555}